### ISSUE TITLE
Cannot select BTC on pick_coin step

### ISSUE THREAD

**Issue by chazmcgarvey** [CypherpunkPay/CypherpunkPay#1]
Stuck at `wait_a_sec=true`

Possibly related unhandled exception:

```
2021-07-19 22:34:13,190 INFO  Starting CypherpunkPay 1.0.1
2021-07-19 22:34:13,191 INFO  Reading config myconfig.ini
2021-07-19 22:34:13,191 INFO  Found wallet config: mainnet btc
2021-07-19 22:34:13,192 INFO  Connecting to database cypherpunkpay.sqlite3
2021-07-19 22:34:13,192 INFO  Migrating database cypherpunkpay.sqlite3 ...
2021-07-19 22:34:13,215 INFO  Migration done.
2021-07-19 22:34:13,261 INFO  Importing wallet descriptor to your Bitcoin Core wallet...
2021-07-19 22:34:21,818 INFO  Successfully connected to Bitcoin Core wallet (cypherpunkpay-wallet-XXX)
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/home/chaz/.pyenv/versions/3.9.6/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/chaz/.pyenv/versions/3.9.6/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chaz/.cache/pypoetry/virtualenvs/cypherpunkpay-ETuIgcZD-py3.9/lib/python3.9/site-packages/apscheduler/schedulers/blocking.py", line 32, in _main_loop
    wait_seconds = self._process_jobs()
  File "/home/chaz/.cache/pypoetry/virtualenvs/cypherpunkpay-ETuIgcZD-py3.9/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 975, in _process_jobs
    run_times = job._get_run_times(now)
  File "/home/chaz/.cache/pypoetry/virtualenvs/cypherpunkpay-ETuIgcZD-py3.9/lib/python3.9/site-packages/apscheduler/job.py", line 135, in _get_run_times
    next_run_time = self.trigger.get_next_fire_time(next_run_time, now)
  File "/home/chaz/.cache/pypoetry/virtualenvs/cypherpunkpay-ETuIgcZD-py3.9/lib/python3.9/site-packages/apscheduler/triggers/interval.py", line 66, in get_next_fire_time
    return self.timezone.normalize(next_fire_time)
  File "/home/chaz/.cache/pypoetry/virtualenvs/cypherpunkpay-ETuIgcZD-py3.9/lib/python3.9/site-packages/pytz/tzinfo.py", line 252, in normalize
    offset = dt.tzinfo._utcoffset
AttributeError: 'datetime.timezone' object has no attribute '_utcoffset'
2021-07-19 22:34:21,898 INFO  Admin panel DISABLED (see /etc/cypherpunkpay.conf)
2021-07-19 22:34:21,924 INFO  Serving on http://127.0.0.1:8080
```

**Comment by CypherpunkDev** [comment]
Thank you for this bug report. I am looking into it and will get back shortly.

**Comment by CypherpunkDev** [comment]
How did you install CypherpunkPay? The paths indicate some kind of custom install or development environment.

Please try installing from official packages and let me know if that works for you:
https://cypherpunkpay.org/installation/quick-start/

Feel free to reopen if this doesn't help.

**Comment by CypherpunkDev** [comment]
OK I recreated the issue. It happens when your machine is not in UTC. Working on a fix.

**Comment by CypherpunkDev** [comment]
I released a new version with a fix. Thanks again for your bug report.

**Comment by chazmcgarvey** [comment]
> How did you install CypherpunkPay? The paths indicate some kind of custom install or development environment.

To play around with Cypherpunkpay I just used [pyenv](https://github.com/pyenv/pyenv) to install a new python in my homedir. The steps I took are essentially this:

```sh
pyenv install 3.9.6
pyenv local 3.9.6
pip install poetry
poetry install
$EDITOR myconfig.ini
poetry run cypherpunkpay --config myconfig.ini
```

I did this on Gentoo Linux so the official packages don't help me much, but it's no problem. It's pretty easy to get Python apps running on any Linux. If I like CypherpunkPay enough to deploy it for real, I might use the official package in a Debian container. Or I might do something like the above in an Alpine container (without pyenv). The simplicity of this project allows for many possibilities.

Now that you've fixed the timezone issue, I'll take another look when I get a moment.

**Comment by CypherpunkDev** [comment]
I'll just add the official deb installer does some nice things like auto creating default configs, systemd service and even generating a testnet wallet so user can immediately get the software running and then safely iterate towards mainnet / production setup.

I look forward for your feedback.

**Comment by pitbullcan** [comment]
I do not now if this fix is already applied to the original repo as I still have this issue even though my Time zone is UTC
